### ISSUE TITLE
正在启动中的服务也会被清理

### ISSUE THREAD

**Issue by liuymzz** [tom6886/ConsulClear#1]
哈罗，把你这个应用稍微改造了一下，做成了自动清空无效服务，结果发现正在启动中的服务也被识别成了无效服务，然后就将正在启动中的服务也清理掉了，导致服务不能正常启动。
这貌似是因为consul把正在启动中的服务当成了已失效的服务，有没有啥办法避免这种情况，google好像也没相关的信息。

**Comment by tom6886** [comment]
刚注册到Consul还没进行健康检查的服务也会被标记为critical，所以会出现这种情况，但是这样的服务它的报错信息output显示为空，所以你清理服务时可以过滤掉最后几条output为空的服务
